# Generated by Django 4.2.6 on 2023-10-15 16:57

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_setup', '0007_alter_menulink_site_setup'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetup',
            name='background_color',
            field=colorfield.fields.ColorField(default='#ffffff', image_field=None, max_length=25, samples=None),
        ),
        migrations.AddField(
            model_name='sitesetup',
            name='footer_color',
            field=colorfield.fields.ColorField(default='#000000', image_field=None, max_length=25, samples=None),
        ),
        migrations.AddField(
            model_name='sitesetup',
            name='header_color',
            field=colorfield.fields.ColorField(default='#ffffff', image_field=None, max_length=25, samples=None),
        ),
        migrations.AddField(
            model_name='sitesetup',
            name='menu_color',
            field=colorfield.fields.ColorField(default='#ffff00', image_field=None, max_length=25, samples=None),
        ),
    ]
