# Generated by Django 4.2.6 on 2023-10-15 18:12

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_delete_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorCustom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_background', colorfield.fields.ColorField(default='#ffffff', image_field=None, max_length=25, samples=None, verbose_name='Cor de fundo')),
                ('color_header', colorfield.fields.ColorField(default='#9999ff', image_field=None, max_length=25, samples=None, verbose_name='Cor do cabeçalho')),
                ('color_menu', colorfield.fields.ColorField(default='#ffff00', image_field=None, max_length=25, samples=None, verbose_name='Cor do menu')),
                ('color_footer', colorfield.fields.ColorField(default='#ffffff', image_field=None, max_length=25, samples=None, verbose_name='Cor do rodapé')),
                ('color_font', colorfield.fields.ColorField(default='#ffffff', image_field=None, max_length=25, samples=None, verbose_name='Cor da Fonte')),
            ],
        ),
    ]
