# Generated by Django 4.2.6 on 2023-10-17 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_colorcustom'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ColorCustom',
        ),
    ]
